teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 5.0
    scale_linear_turbo:
      x: 7.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 50.0

    enable_button: 4  # L2 shoulder button
    enable_turbo_button: 5  # L1 shoulder button